/*=============================================================================
File Name : RTC_defines.h
Purpose   : Common RTC-related macros for LPC21xx ARM7 microcontrollers
             (Used for Real Time Clock configuration and timing calculations)

=============================================================================*/
/*=============================================================================
                     SYSTEM CLOCK CONFIGURATION
=============================================================================*/

/*
FOSC = Main Oscillator Frequency

This is the frequency generated by the external crystal oscillator
connected to the microcontroller.

Crystal Frequency = 12 MHz   Meaning: 12,000,000 oscillations per second

This clock is the primary input clock source for PLL and CPU clock generation.
*/

#define FOSC 12000000
/*
CCLK = CPU Clock Frequency

The PLL (Phase Locked Loop) multiplies the oscillator frequency
to generate a higher-speed clock for the ARM CPU core.

Formula: CCLK = FOSC × PLL Multiplier   Here:  12 MHz × 5 = 60 MHz

Meaning: ARM core executes instructions at 60 MHz.
*/
#define CCLK (FOSC*5)

/*
PCLK = Peripheral Clock Frequency

Peripheral modules such as: Timers, UART, SPI, RTC, ADC......

do NOT always run at CPU clock speed.
The VPBDIV register divides CCLK to generate PCLK.

PCLK = CCLK / 4   So:  60 MHz / 4 = 15 MHz

Meaning:  All peripherals receive a 15 MHz clock.
*/
#define PCLK (CCLK/4)

/*=============================================================================
                    RTC PRESCALER CALCULATION MACROS
=============================================================================*/

/*
RTC (Real Time Clock) internally requires a precise 1 Hz clock.RTC must increment time once every second.

But currently: Peripheral clock = 15 MHz.So we must divide 15 MHz down to 1 Hz.

RTC hardware contains:
1. Integer Prescaler
2. Fractional Prescaler

These two together accurately generate a 32768 Hz RTC clock.

PREINT_VAL = Integer Prescaler Value

Formuls: PREINT = (PCLK / 32768) - 1.  PCLK = 15,000,000

Calculation: 15000000 / 32768 = 457.76.  PREINT = 457.76 - 1 =~456

This integer prescaler divides the main peripheral clock
into near-32768 Hz timing ticks.

PREFRAC_VAL = Fractional Prescaler Value

15 MHz cannot be divided exactly by 32768, some fractional error remains.

PREFRAC = PCLK - ((PREINT + 1) × 32768)

This ensures long-term RTC accuracy.
*/
#define PREINT_VAL (int)((PCLK/32768)-1)
#define PREFRAC_VAL (PCLK-((PREINT_VAL+1)*32768))

/*=============================================================================
                     RTC CONTROL REGISTER BIT DEFINITIONS
=============================================================================*/

/*
RTC_ENABLE = RTC Clock Enable Bit

RTC Control Register (CCR)
Bit 0 controls RTC operation. 
Bit = 1: RTC counters start running.
Bit = 0: RTC stops counting

This starts:
- seconds counter, minutes counter, hours counter, calendar logic......
*/
#define RTC_ENABLE (1<<0)

/*
RTC_RESET = RTC Reset Bit

RTC Control Register (CCR)
Bit 1 resets all RTC counters.

Bit = 1: RTC counters reset to default values
Bit = 0: Normal operation

This clears:
- seconds, minutes, hours, calender counters....
*/
#define RTC_RESET (1<<1)

/*=============================================================================
        ONLY FOR LPC2148: RTC CLOCK SOURCE CONTROL
=============================================================================*/

/*
RTC_CLKSRC = RTC Clock Source Selection Bit. ONLY available in LPC2148.

CCR Register Bit 4 selects RTC clock source.
Bit = 1: RTC uses external 32.768 kHz RTC crystal
Bit = 0: RTC uses internal peripheral clock (PCLK)
*/
#define RTC_CLKSRC (1<<4)

/*=============================================================================
                     CPU SELECTION MACROS
=============================================================================*/
/*
These macros are useful when supporting multiple LPC21xx devices
using the same project source code.

Conditional compilation can be used here.
Macro representing LPC2129 & LPC2148 controller
*/
#define LPC2129 0
#define LPC2148 1

/*
Select target CPU for compilation.

Compiler can use this macro for conditional compilation
*/
#define CPU LPC2148
